name: Test

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
    # Fix line endings
    - if: runner.os == 'windows'
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v2

    - if: runner.os == 'macos'
      run: brew install shellcheck 
    - if: runner.os == 'linux'
      run: sudo apt install -y shellcheck
    - if: runner.os == 'windows'
      run: choco install --yes shellcheck

    - if: runner.os == 'macos'
      run: make
    - if: runner.os == 'linux'
      run: make
    - if: runner.os == 'windows'
      run: make
      shell: bash
